version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: project_advance_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eco_monitoring_db
      MYSQL_USER: api_user
      MYSQL_PASSWORD: apipassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Updated this line to point directly to your SQL file
      - /home/jammes/Desktop/dbFinalProject/eco_monitoring_db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
